### ISSUE TITLE
Point order seems wrong

### ISSUE THREAD

**Issue by YunzhongTianjing** [yuripourre/e-motion#11]
Is a bug there?The order of the points seems wrong in method ajustPoints of PositCoplanarModifier.java
''		Point2D a = points.get(0);
		imagePoints.get(0).setLocation(a.getX()-w/2, h/2-a.getY());		
		Point2D b = points.get(1);
		imagePoints.get(1).setLocation(b.getX()-w/2, h/2-b.getY());		
		Point2D d = points.get(3);
		imagePoints.get(2).setLocation(d.getX()-w/2, h/2-d.getY());		
		Point2D c = points.get(2);
		imagePoints.get(3).setLocation(c.getX()-w/2, h/2-c.getY());
''

**Comment by yuripourre** [comment]
The image points order are related to _model_ points found in [CoplanarPosit](https://github.com/yuripourre/e-motion/blob/master/src/main/java/br/com/etyllica/motion/modifier/posit/CoplanarPosit.java#L29)

```
model.add(new Vec3D(-half,  half, 0.0));
model.add(new Vec3D( half,  half, 0.0));
model.add(new Vec3D( half,  -half, 0.0));
model.add(new Vec3D(-half,  -half, 0.0));
```

I made the modifier in a different order but I think the natural way is follow the same order.

Thank you for report that. I will fix this soon (I will have to change it in [Luvmotion](https://github.com/yuripourre/luvmotion) too).
